/**
 * Hero ability definitions. Pure data; the sim applies the effects.
 */

import type { HeroAbilityId } from '../sim/state';

export interface HeroAbility {
  id: HeroAbilityId;
  name: string;
  description: string;
  /** Effect the simulation applies when this ability is active. */
  effect: 'leadership' | 'fortify' | 'rally' | 'scout';
}

export const HERO_ABILITIES: Record<HeroAbilityId, HeroAbility> = {
  leadership: {
    id: 'leadership',
    name: 'Leadership',
    description: '+1 attack to all friendly units on the map.',
    effect: 'leadership',
  },
  fortify: {
    id: 'fortify',
    name: 'Fortify',
    description: '+2 defense to the stack for one turn.',
    effect: 'fortify',
  },
  rally: {
    id: 'rally',
    name: 'Rally',
    description: 'Restore 2 HP to every unit in the stack.',
    effect: 'rally',
  },
  scout: {
    id: 'scout',
    name: 'Scout',
    description: 'Reveal fog of war in a 5-tile radius.',
    effect: 'scout',
  },
};

/** Pool of randomly-chosen hero names. */
export const HERO_NAMES: ReadonlyArray<string> = [
  'Aldric', 'Brynn', 'Cedric', 'Dorian', 'Elena', 'Fenris', 'Gideon', 'Helena',
  'Isolde', 'Jasper', 'Kira', 'Lysander', 'Morgana', 'Nyx', 'Orion', 'Phoenix',
  'Quinn', 'Raven', 'Seraphina', 'Theron', 'Vex', 'Wren', 'Xander', 'Yara', 'Zephyr',
];

/** Random level 1 hero for a faction. Generated by the sim, not stored. */
export function pickRandomHeroName(seed = Math.random()): string {
  const idx = Math.floor(seed * HERO_NAMES.length);
  return HERO_NAMES[idx] ?? 'Aldric';
}
